// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'delay',
  version: 1,
  name: 'ECHO',
  subtitle: 'DELAY',
  category: 'DELAY',
  order: 6,
  color: '#31666b',
  panel: '#9bcdd0',
  width: 256,
  layout: 'studio',
  footer: 'FIELD / 07',
  inputs: [
    {
      id: 'in',
      label: 'SIGNAL',
      kind: 'audio',
      x: 32,
      y: 80,
      labelPosition: 'below',
    },
    {
      id: 'time',
      label: 'TIME',
      kind: 'cv',
      x: 32,
      y: 176,
      labelPosition: 'below',
    },
    {
      id: 'clock',
      label: 'SYNC',
      kind: 'gate',
      x: 32,
      y: 273,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'out',
      label: 'MIX',
      kind: 'audio',
      x: 223,
      y: 258,
      labelPosition: 'below',
    },
    {
      id: 'wet',
      label: 'WET',
      kind: 'audio',
      x: 223,
      y: 329,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'time',
      label: 'TIME',
      min: 0.01,
      max: 2,
      default: 0.32,
      log: true,
      unit: 's',
    },
    {
      id: 'feedback',
      label: 'FEEDBACK',
      min: 0,
      max: 0.95,
      default: 0.35,
    },
    {
      id: 'tone',
      label: 'TONE',
      min: 200,
      max: 16000,
      default: 6000,
      log: true,
      unit: 'Hz',
    },
    {
      id: 'mix',
      label: 'MIX',
      min: 0,
      max: 1,
      default: 0.3,
    },
    {
      id: 'division',
      label: 'SYNC',
      min: 0,
      max: 4,
      default: 2,
      step: 1,
      smooth: false,
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
