// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'stereo-mixer',
  version: 1,
  name: 'HARBOUR',
  subtitle: 'STEREO MIX / SEND',
  category: 'STEREO MIX',
  order: 8.5,
  color: '#365875',
  panel: '#abc4d3',
  width: 480,
  layout: 'studio',
  headerLayout: 'compact',
  portStyle: 'badge',
  inputs: [
    {
      id: 'left1',
      label: '1 L',
      x: 37,
      y: 77,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'right1',
      label: '1 R',
      x: 83,
      y: 77,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'left2',
      label: '2 L',
      x: 139,
      y: 77,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'right2',
      label: '2 R',
      x: 185,
      y: 77,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'left3',
      label: '3 L',
      x: 241,
      y: 77,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'right3',
      label: '3 R',
      x: 287,
      y: 77,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'returnL',
      label: 'RETURN L',
      x: 360,
      y: 77,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'returnR',
      label: 'RETURN R',
      x: 432,
      y: 77,
      kind: 'audio',
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'sendL',
      label: 'SEND L',
      x: 360,
      y: 278,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'sendR',
      label: 'SEND R',
      x: 432,
      y: 278,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'left',
      label: 'MAIN L',
      x: 360,
      y: 340,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'right',
      label: 'MAIN R',
      x: 432,
      y: 340,
      kind: 'audio',
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'level1',
      label: 'LEVEL 1',
      min: 0,
      max: 1,
      default: 0.7,
    },
    {
      id: 'pan1',
      label: 'PAN 1',
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: 'send1',
      label: 'SEND 1',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'level2',
      label: 'LEVEL 2',
      min: 0,
      max: 1,
      default: 0.7,
    },
    {
      id: 'pan2',
      label: 'PAN 2',
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: 'send2',
      label: 'SEND 2',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'level3',
      label: 'LEVEL 3',
      min: 0,
      max: 1,
      default: 0.7,
    },
    {
      id: 'pan3',
      label: 'PAN 3',
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: 'send3',
      label: 'SEND 3',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'return',
      label: 'RETURN',
      min: 0,
      max: 1,
      default: 0.7,
    },
    {
      id: 'master',
      label: 'MASTER',
      min: 0,
      max: 1,
      default: 0.8,
    },
  ],
};
