// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'a156',
  version: 1,
  name: 'PRISM\u00b2',
  subtitle: 'DUAL QUANTISER',
  color: '#7b4c72',
  panel: '#d5b3cc',
  width: 128,
  layout: 'faceplate',
  footer: 'FIELD / ARCHIVE',
  inputs: [
    {
      id: 'cv1',
      label: 'CV In',
      x: 29,
      y: 85,
      kind: 'cv',
    },
    {
      id: 'trig1',
      label: 'Trig. In',
      x: 29,
      y: 128,
      kind: 'gate',
    },
    {
      id: 'cv2',
      label: 'CV In',
      x: 29,
      y: 191,
      kind: 'cv',
    },
    {
      id: 'trig2',
      label: 'Trig. In',
      x: 29,
      y: 240,
      kind: 'gate',
    },
    {
      id: 'transpose',
      label: 'Transpose',
      x: 29,
      y: 320,
      kind: 'cv',
    },
  ],
  outputs: [
    {
      id: 'out1',
      label: 'CV Out',
      x: 98,
      y: 85,
      kind: 'cv',
    },
    {
      id: 'trigOut1',
      label: 'Trig. Out',
      x: 98,
      y: 128,
      kind: 'gate',
    },
    {
      id: 'out2',
      label: 'CV Out',
      x: 98,
      y: 191,
      kind: 'cv',
    },
    {
      id: 'trigOut2',
      label: 'Trig. Out',
      x: 98,
      y: 240,
      kind: 'gate',
    },
  ],
  params: [
    {
      id: 'scale',
      label: 'Scale',
      min: 0,
      max: 2,
      default: 1,
      step: 1,
      smooth: false,
    },
    {
      id: 'mode',
      label: 'Notes',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
    {
      id: 'extension',
      label: 'Extension',
      min: 0,
      max: 2,
      default: 1,
      step: 1,
      smooth: false,
    },
  ],
  hidden: true,
};
