// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'lfo',
  version: 1,
  name: 'DRIFT',
  subtitle: 'LFO',
  category: 'LFO',
  order: 2,
  color: '#635084',
  panel: '#c5b7dc',
  width: 192,
  layout: 'studio',
  footer: 'FIELD / 03',
  inputs: [
    {
      id: 'reset',
      label: 'RESET',
      kind: 'gate',
      x: 32,
      y: 282,
      labelPosition: 'below',
    },
    {
      id: 'rate',
      label: 'RATE',
      kind: 'cv',
      x: 32,
      y: 203,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'sine',
      label: 'SINE',
      kind: 'cv',
      x: 160,
      y: 86,
      labelPosition: 'below',
    },
    {
      id: 'triangle',
      label: 'TRI',
      kind: 'cv',
      x: 160,
      y: 181,
      labelPosition: 'below',
    },
    {
      id: 'square',
      label: 'PULSE',
      kind: 'gate',
      x: 160,
      y: 276,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'rate',
      label: 'RATE',
      min: 0.015,
      max: 35,
      default: 0.3,
      log: true,
      unit: 'Hz',
    },
    {
      id: 'depth',
      label: 'DEPTH',
      min: 0,
      max: 5,
      default: 5,
      unit: 'V',
    },
    {
      id: 'polarity',
      label: 'POLARITY',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
