// Generated by npm run modules:sync. Edit the module folders instead.
import module0 from './a110';
import module1 from './a124';
import module2 from './a1323';
import module3 from './a138';
import module4 from './a155';
import module5 from './a156';
import module6 from './a1832';
import module7 from './clock';
import module8 from './cv-mixer';
import module9 from './delay';
import module10 from './distortion';
import module11 from './divider';
import module12 from './dual-envelope';
import module13 from './envelope';
import module14 from './filter';
import module15 from './lfo';
import module16 from './logic';
import module17 from './maths';
import module18 from './oscillator';
import module19 from './output';
import module20 from './quantiser';
import module21 from './random';
import module22 from './reverb';
import module23 from './sampler';
import module24 from './sequencer';
import module25 from './shift-register';
import module26 from './slope';
import module27 from './stereo-mixer';
import module28 from './switch';
import module29 from './tape-delay';
import module30 from './vca';
export const MODULES = {
  'a110': module0,
  'a124': module1,
  'a1323': module2,
  'a138': module3,
  'a155': module4,
  'a156': module5,
  'a1832': module6,
  'clock': module7,
  'cv-mixer': module8,
  'delay': module9,
  'distortion': module10,
  'divider': module11,
  'dual-envelope': module12,
  'envelope': module13,
  'filter': module14,
  'lfo': module15,
  'logic': module16,
  'maths': module17,
  'oscillator': module18,
  'output': module19,
  'quantiser': module20,
  'random': module21,
  'reverb': module22,
  'sampler': module23,
  'sequencer': module24,
  'shift-register': module25,
  'slope': module26,
  'stereo-mixer': module27,
  'switch': module28,
  'tape-delay': module29,
  'vca': module30,
};
