// @ts-check
import { createData, restoreData } from './data.js';
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  createData,
  restoreData,
  type: 'sampler',
  version: 1,
  name: 'GRAIN',
  subtitle: 'SAMPLER / GRANULAR',
  category: 'SAMPLER',
  order: 4.5,
  color: '#744971',
  panel: '#d2b5cc',
  width: 400,
  layout: 'studio',
  headerLayout: 'compact',
  portStyle: 'badge',
  inputs: [
    {
      id: 'trigger',
      label: 'TRIG',
      x: 40,
      y: 150,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'pitch',
      label: '1V/OCT',
      x: 40,
      y: 210,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'position',
      label: 'POS CV',
      x: 40,
      y: 270,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'gate',
      label: 'GATE',
      x: 40,
      y: 332,
      kind: 'gate',
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'left',
      label: 'LEFT',
      x: 360,
      y: 150,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'right',
      label: 'RIGHT',
      x: 360,
      y: 212,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'end',
      label: 'END',
      x: 360,
      y: 274,
      kind: 'gate',
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'position',
      label: 'POSITION',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'length',
      label: 'LENGTH',
      min: 0.005,
      max: 1,
      default: 1,
    },
    {
      id: 'tune',
      label: 'TUNE',
      min: -24,
      max: 24,
      default: 0,
      unit: 'st',
    },
    {
      id: 'grain',
      label: 'GRAIN SIZE',
      min: 0.01,
      max: 0.4,
      default: 0.1,
      log: true,
      unit: 's',
    },
    {
      id: 'density',
      label: 'DENSITY',
      min: 1,
      max: 40,
      default: 12,
      unit: 'Hz',
    },
    {
      id: 'spray',
      label: 'SPRAY',
      min: 0,
      max: 1,
      default: 0.1,
    },
    {
      id: 'mode',
      label: 'MODE',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'reverse',
      label: 'DIRECTION',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
  ],
};
