// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'switch',
  version: 1,
  name: 'JUNCTION',
  subtitle: 'SWITCH / 4',
  category: 'SWITCH',
  order: 12.1,
  color: '#876024',
  panel: '#e7ce8b',
  width: 360,
  layout: 'studio',
  headerLayout: 'compact',
  portStyle: 'badge',
  inputs: [
    {
      id: 'in1',
      label: '1',
      x: 32,
      y: 75,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'in2',
      label: '2',
      x: 32,
      y: 137,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'in3',
      label: '3',
      x: 32,
      y: 199,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'in4',
      label: '4',
      x: 32,
      y: 261,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'signal',
      label: 'COMMON',
      x: 202,
      y: 323,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'address',
      label: 'ADDRESS',
      x: 105,
      y: 191,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'clock',
      label: 'CLOCK',
      x: 96,
      y: 323,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'reset',
      label: 'RESET',
      x: 149,
      y: 323,
      kind: 'gate',
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'out1',
      label: '1',
      x: 328,
      y: 75,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'out2',
      label: '2',
      x: 328,
      y: 137,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'out3',
      label: '3',
      x: 328,
      y: 199,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'out4',
      label: '4',
      x: 328,
      y: 261,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'out',
      label: 'SELECTED',
      x: 263,
      y: 323,
      kind: 'cv',
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'select',
      label: 'SELECT',
      min: 1,
      max: 4,
      default: 1,
      step: 1,
      smooth: false,
      unit: 'steps',
    },
    {
      id: 'length',
      label: 'STAGES',
      min: 1,
      max: 4,
      default: 4,
      step: 1,
      smooth: false,
    },
    {
      id: 'mode',
      label: 'ADDRESS',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
  ],
};
