// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  version: 1,
  hidden: true,
  mark: '⋀',
  type: 'slope',
  name: 'SLOPE',
  subtitle: 'FUNCTION',
  color: '#7b602b',
  panel: '#e4cf8e',
  width: 184,
  inputs: [
    {
      id: 'trigger',
      label: 'TRIG',
      kind: 'gate',
      x: 32,
      y: 79,
      labelPosition: 'below',
    },
    {
      id: 'time',
      label: 'TIME',
      kind: 'cv',
      x: 32,
      y: 246,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'out',
      label: 'OUT',
      kind: 'cv',
      x: 150,
      y: 246,
      labelPosition: 'below',
    },
    {
      id: 'eoc',
      label: 'EOC',
      kind: 'gate',
      x: 150,
      y: 326,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'rise',
      label: 'RISE',
      min: 0.002,
      max: 8,
      default: 0.008,
      log: true,
      unit: 's',
    },
    {
      id: 'fall',
      label: 'FALL',
      min: 0.005,
      max: 12,
      default: 0.23,
      log: true,
      unit: 's',
    },
    {
      id: 'cycle',
      smooth: false,
      label: 'CYCLE',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
    },
  ],
  layout: 'studio',
  headerLayout: 'compact',
  portStyle: 'badge',
};
