// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'cv-mixer',
  version: 1,
  name: 'BRAID',
  subtitle: 'MIX · INVERT · OFFSET',
  category: 'CV MIXER',
  order: 2.5,
  color: '#35665d',
  panel: '#9fcbbd',
  width: 304,
  layout: 'studio',
  footer: 'FIELD / 14',
  inputs: [
    {
      id: 'a1',
      label: '1A',
      kind: 'cv',
      x: 28,
      y: 83,
      labelPosition: 'below',
    },
    {
      id: 'b1',
      label: '1B',
      kind: 'cv',
      x: 143,
      y: 83,
      labelPosition: 'below',
    },
    {
      id: 'a2',
      label: '2A',
      kind: 'cv',
      x: 28,
      y: 181,
      labelPosition: 'below',
    },
    {
      id: 'b2',
      label: '2B',
      kind: 'cv',
      x: 143,
      y: 181,
      labelPosition: 'below',
    },
    {
      id: 'a3',
      label: '3A',
      kind: 'cv',
      x: 28,
      y: 279,
      labelPosition: 'below',
    },
    {
      id: 'b3',
      label: '3B',
      kind: 'cv',
      x: 143,
      y: 279,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'out1',
      label: 'OUT 1',
      kind: 'cv',
      x: 272,
      y: 83,
      labelPosition: 'below',
    },
    {
      id: 'out2',
      label: 'OUT 2',
      kind: 'cv',
      x: 272,
      y: 181,
      labelPosition: 'below',
    },
    {
      id: 'out3',
      label: 'OUT 3',
      kind: 'cv',
      x: 272,
      y: 279,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'a1',
      label: '1A',
      min: -1,
      max: 1,
      default: 0,
      unit: 'x',
    },
    {
      id: 'b1',
      label: '1B',
      min: -1,
      max: 1,
      default: 0,
      unit: 'x',
    },
    {
      id: 'a2',
      label: '2A',
      min: -1,
      max: 1,
      default: 0,
      unit: 'x',
    },
    {
      id: 'b2',
      label: '2B',
      min: -1,
      max: 1,
      default: 0,
      unit: 'x',
    },
    {
      id: 'a3',
      label: '3A',
      min: -1,
      max: 1,
      default: 0,
      unit: 'x',
    },
    {
      id: 'b3',
      label: '3B',
      min: -1,
      max: 1,
      default: 0,
      unit: 'x',
    },
    {
      id: 'link12',
      label: 'Mix output 1 into output 2',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'link23',
      label: 'Mix output 2 into output 3',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
