// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'divider',
  version: 1,
  name: 'SPLIT',
  subtitle: 'DIVIDER',
  category: 'DIVIDER',
  order: 10,
  color: '#525b88',
  panel: '#b8bfdf',
  width: 192,
  layout: 'studio',
  footer: 'FIELD / 11',
  inputs: [
    {
      id: 'clock',
      label: 'CLOCK',
      kind: 'gate',
      x: 36,
      y: 78,
      labelPosition: 'below',
    },
    {
      id: 'reset',
      label: 'RESET',
      kind: 'gate',
      x: 36,
      y: 326,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'div2',
      label: '÷2',
      kind: 'gate',
      x: 156,
      y: 80,
      labelPosition: 'below',
    },
    {
      id: 'div3',
      label: '÷3',
      kind: 'gate',
      x: 156,
      y: 160,
      labelPosition: 'below',
    },
    {
      id: 'div4',
      label: '÷4',
      kind: 'gate',
      x: 156,
      y: 240,
      labelPosition: 'below',
    },
    {
      id: 'div8',
      label: '÷8',
      kind: 'gate',
      x: 156,
      y: 320,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'mode',
      label: 'PULSE',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'offset',
      label: 'OFFSET',
      min: 0,
      max: 7,
      default: 0,
      step: 1,
      smooth: false,
      unit: 'steps',
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
