// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'oscillator',
  version: 2,
  name: 'ORBIT',
  subtitle: 'VCO',
  category: 'VCO',
  order: 4,
  color: '#895129',
  panel: '#e9bb84',
  width: 232,
  layout: 'studio',
  footer: 'FIELD / 05',
  inputs: [
    {
      id: 'pitch',
      label: '1V/OCT',
      kind: 'cv',
      x: 30,
      y: 80,
      labelPosition: 'below',
    },
    {
      id: 'fm',
      label: 'FM',
      kind: 'cv',
      x: 30,
      y: 246,
      labelPosition: 'below',
    },
    {
      id: 'pwm',
      label: 'PWM',
      kind: 'cv',
      x: 30,
      y: 325,
      labelPosition: 'below',
    },
    {
      id: 'sync',
      label: 'SYNC',
      kind: 'gate',
      x: 30,
      y: 164,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'sine',
      label: 'SINE',
      kind: 'audio',
      x: 202,
      y: 80,
      labelPosition: 'below',
    },
    {
      id: 'triangle',
      label: 'TRI',
      kind: 'audio',
      x: 202,
      y: 162,
      labelPosition: 'below',
    },
    {
      id: 'saw',
      label: 'SAW',
      kind: 'audio',
      x: 202,
      y: 244,
      labelPosition: 'below',
    },
    {
      id: 'pulse',
      label: 'PULSE',
      kind: 'audio',
      x: 202,
      y: 326,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'tune',
      label: 'TUNE',
      min: -36,
      max: 36,
      default: -12,
      step: 1,
      unit: 'st',
    },
    {
      id: 'fine',
      label: 'FINE',
      min: -100,
      max: 100,
      default: 0,
      unit: 'ct',
    },
    {
      id: 'fm',
      label: 'FM',
      min: 0,
      max: 1,
      default: 0.1,
    },
    {
      id: 'width',
      label: 'WIDTH',
      min: 0.02,
      max: 0.98,
      default: 0.5,
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
