// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'a110',
  version: 1,
  name: 'ORBIT+',
  subtitle: 'VCO',
  color: '#895129',
  panel: '#e9bb84',
  width: 160,
  layout: 'faceplate',
  footer: 'FIELD / ARCHIVE',
  inputs: [
    {
      id: 'sync',
      label: 'Sync',
      x: 28,
      y: 68,
      kind: 'gate',
    },
    {
      id: 'cv1',
      label: 'CV 1',
      x: 28,
      y: 121,
      kind: 'cv',
    },
    {
      id: 'cv2',
      label: 'CV 2',
      x: 28,
      y: 177,
      kind: 'cv',
    },
    {
      id: 'pw1',
      label: 'PW 1',
      x: 28,
      y: 232,
      kind: 'cv',
    },
    {
      id: 'pw2',
      label: 'PW 2',
      x: 28,
      y: 287,
      kind: 'cv',
    },
  ],
  outputs: [
    {
      id: 'saw',
      label: 'SAW',
      x: 25,
      y: 352,
      kind: 'audio',
    },
    {
      id: 'pulse',
      label: 'PULSE',
      x: 62,
      y: 352,
      kind: 'audio',
    },
    {
      id: 'triangle',
      label: 'TRI',
      x: 99,
      y: 352,
      kind: 'audio',
    },
    {
      id: 'sine',
      label: 'SINE',
      x: 136,
      y: 352,
      kind: 'audio',
    },
  ],
  params: [
    {
      id: 'range',
      label: 'Range',
      min: -2,
      max: 2,
      default: -1,
      step: 1,
      smooth: false,
      unit: 'oct',
    },
    {
      id: 'tune',
      label: 'Tune',
      min: -6,
      max: 6,
      default: 0,
      unit: 'st',
    },
    {
      id: 'cv2',
      label: 'CV 2',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'pw',
      label: 'PW',
      min: 0.02,
      max: 0.98,
      default: 0.5,
    },
    {
      id: 'pwm',
      label: 'PWM',
      min: 0,
      max: 1,
      default: 0,
    },
  ],
  hidden: true,
};
