// @ts-check
/** @type {import('../types').ModuleDefinition} */
export const definition = {
  type: 'vca',
  version: 2,
  name: 'VEIL',
  subtitle: 'VCA / 2',
  category: 'DUAL VCA',
  order: 0,
  color: '#35584c',
  panel: '#aacfb7',
  width: 184,
  layout: 'studio',
  footer: 'FIELD / 01',
  inputs: [
    {
      id: 'in',
      label: 'IN A',
      kind: 'audio',
      x: 36,
      y: 173,
      labelPosition: 'below',
    },
    {
      id: 'cv',
      label: 'CV A',
      kind: 'cv',
      x: 92,
      y: 173,
      labelPosition: 'below',
    },
    {
      id: 'in2',
      label: 'IN B',
      kind: 'audio',
      x: 36,
      y: 329,
      labelPosition: 'below',
    },
    {
      id: 'cv2',
      label: 'CV B',
      kind: 'cv',
      x: 92,
      y: 329,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'out',
      label: 'OUT A',
      kind: 'audio',
      x: 148,
      y: 173,
      labelPosition: 'below',
    },
    {
      id: 'out2',
      label: 'OUT B',
      kind: 'audio',
      x: 148,
      y: 329,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'gain',
      label: 'BIAS',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'depth',
      label: 'CV',
      min: 0,
      max: 1,
      default: 1,
    },
    {
      id: 'curve',
      label: 'CURVE',
      min: 0,
      max: 1,
      default: 0.2,
    },
    {
      id: 'gain2',
      label: 'BIAS',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'depth2',
      label: 'CV',
      min: 0,
      max: 1,
      default: 1,
    },
    {
      id: 'curve2',
      label: 'CURVE',
      min: 0,
      max: 1,
      default: 0.2,
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
