// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'tape-delay',
  version: 1,
  name: 'SPOOL',
  subtitle: 'LO-FI TAPE DELAY',
  category: 'TAPE DELAY',
  order: 6.5,
  color: '#68442f',
  panel: '#d7b083',
  width: 344,
  layout: 'studio',
  footer: 'FIELD / 13',
  inputs: [
    {
      id: 'in',
      label: 'SIGNAL',
      kind: 'audio',
      x: 30,
      y: 83,
      labelPosition: 'below',
    },
    {
      id: 'time',
      label: 'TIME',
      kind: 'cv',
      x: 30,
      y: 172,
      labelPosition: 'below',
    },
    {
      id: 'feedback',
      label: 'REGEN',
      kind: 'cv',
      x: 180,
      y: 172,
      labelPosition: 'below',
    },
    {
      id: 'clock',
      label: 'SYNC',
      kind: 'gate',
      x: 30,
      y: 266,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'out',
      label: 'MIX',
      kind: 'audio',
      x: 312,
      y: 250,
      labelPosition: 'below',
    },
    {
      id: 'wet',
      label: 'WET',
      kind: 'audio',
      x: 312,
      y: 327,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'time',
      label: 'TIME',
      min: 0.03,
      max: 2,
      default: 0.38,
      log: true,
      unit: 's',
    },
    {
      id: 'feedback',
      label: 'REGEN',
      min: 0,
      max: 1.12,
      default: 0.55,
    },
    {
      id: 'drive',
      label: 'DRIVE',
      min: 1,
      max: 12,
      default: 2.2,
      log: true,
      unit: 'x',
    },
    {
      id: 'tone',
      label: 'TONE',
      min: 400,
      max: 12000,
      default: 4500,
      log: true,
      unit: 'Hz',
    },
    {
      id: 'age',
      label: 'WEAR',
      min: 0,
      max: 1,
      default: 0.4,
    },
    {
      id: 'wow',
      label: 'WOW',
      min: 0,
      max: 1,
      default: 0.35,
    },
    {
      id: 'hiss',
      label: 'HISS',
      min: 0,
      max: 1,
      default: 0.12,
    },
    {
      id: 'mix',
      label: 'MIX',
      min: 0,
      max: 1,
      default: 0.4,
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
