// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'clock',
  version: 1,
  name: 'TICK',
  subtitle: 'CLOCK',
  category: 'CLOCK',
  order: 9,
  color: '#82702d',
  panel: '#e9d48e',
  width: 184,
  layout: 'studio',
  footer: 'FIELD / 10',
  inputs: [
    {
      id: 'reset',
      label: 'RESET',
      kind: 'gate',
      x: 32,
      y: 316,
      labelPosition: 'below',
    },
    {
      id: 'run',
      label: 'RUN',
      kind: 'gate',
      x: 32,
      y: 211,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'clock',
      label: 'CLOCK',
      kind: 'gate',
      x: 151,
      y: 211,
      labelPosition: 'below',
    },
    {
      id: 'reset',
      label: 'RESET',
      kind: 'gate',
      x: 151,
      y: 316,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'bpm',
      label: 'TEMPO',
      min: 20,
      max: 300,
      default: 104,
      step: 1,
      unit: 'BPM',
    },
    {
      id: 'swing',
      label: 'SWING',
      min: 0,
      max: 0.65,
      default: 0,
    },
    {
      id: 'rate',
      label: 'RATE',
      min: 0,
      max: 3,
      default: 2,
      step: 1,
      smooth: false,
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
