// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'a1323',
  version: 1,
  name: 'VEIL²',
  subtitle: 'DUAL VCA',
  color: '#35584c',
  panel: '#aacfb7',
  width: 128,
  layout: 'faceplate',
  footer: 'FIELD / ARCHIVE',
  inputs: [
    {
      id: 'cv1',
      label: 'CV In',
      x: 27,
      y: 78,
      kind: 'cv',
    },
    {
      id: 'in1',
      label: 'In',
      x: 27,
      y: 133,
      kind: 'audio',
    },
    {
      id: 'cv2',
      label: 'CV In',
      x: 27,
      y: 237,
      kind: 'cv',
    },
    {
      id: 'in2',
      label: 'In',
      x: 27,
      y: 292,
      kind: 'audio',
    },
  ],
  outputs: [
    {
      id: 'out1',
      label: 'Out',
      x: 27,
      y: 179,
      kind: 'audio',
    },
    {
      id: 'out2',
      label: 'Out',
      x: 27,
      y: 337,
      kind: 'audio',
    },
  ],
  params: [
    {
      id: 'cv1',
      label: 'CV',
      min: 0,
      max: 1,
      default: 1,
    },
    {
      id: 'gain1',
      label: 'Gain',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'curve1',
      label: 'Channel 1 response',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'cv2',
      label: 'CV',
      min: 0,
      max: 1,
      default: 1,
    },
    {
      id: 'gain2',
      label: 'Gain',
      min: 0,
      max: 1,
      default: 0,
    },
    {
      id: 'curve2',
      label: 'Channel 2 response',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
  ],
  hidden: true,
};
