// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'filter',
  version: 2,
  name: 'SIEVE',
  subtitle: 'VCF',
  category: 'VCF',
  order: 5,
  color: '#61723f',
  panel: '#c9d99b',
  width: 224,
  layout: 'studio',
  footer: 'FIELD / 06',
  inputs: [
    {
      id: 'in',
      label: 'SIGNAL',
      kind: 'audio',
      x: 32,
      y: 82,
      labelPosition: 'below',
    },
    {
      id: 'cutoff',
      label: 'FREQ',
      kind: 'cv',
      x: 32,
      y: 191,
      labelPosition: 'below',
    },
    {
      id: 'vca',
      label: 'LEVEL',
      kind: 'cv',
      x: 32,
      y: 300,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'low',
      label: 'LOW',
      kind: 'audio',
      x: 192,
      y: 111,
      labelPosition: 'below',
    },
    {
      id: 'band',
      label: 'BAND',
      kind: 'audio',
      x: 192,
      y: 210,
      labelPosition: 'below',
    },
    {
      id: 'high',
      label: 'HIGH',
      kind: 'audio',
      x: 192,
      y: 309,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'cutoff',
      label: 'CUTOFF',
      min: 30,
      max: 16000,
      default: 900,
      log: true,
      unit: 'Hz',
    },
    {
      id: 'resonance',
      label: 'RES',
      min: 0,
      max: 0.95,
      default: 0.28,
    },
    {
      id: 'depth',
      label: 'FM',
      min: -5,
      max: 5,
      default: 2,
      unit: 'oct',
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
