// @ts-check
/** @type {import('../types').ModuleDefinition} */
export const definition = {
  type: 'dual-envelope',
  version: 1,
  name: 'SPROUT',
  subtitle: 'ENV / 2',
  category: 'DUAL AD ENV',
  order: 1.1,
  color: '#85542e',
  panel: '#e4c39b',
  width: 232,
  layout: 'studio',
  headerLayout: 'compact',
  portStyle: 'badge',
  inputs: [
    {
      id: 'trigger1',
      label: 'TRIG A',
      kind: 'gate',
      x: 34,
      y: 181,
      labelPosition: 'below',
    },
    {
      id: 'trigger2',
      label: 'TRIG B',
      kind: 'gate',
      x: 34,
      y: 337,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'env1',
      label: 'ENV A',
      kind: 'cv',
      x: 116,
      y: 181,
      labelPosition: 'below',
    },
    {
      id: 'end1',
      label: 'END A',
      kind: 'gate',
      x: 198,
      y: 181,
      labelPosition: 'below',
    },
    {
      id: 'env2',
      label: 'ENV B',
      kind: 'cv',
      x: 116,
      y: 337,
      labelPosition: 'below',
    },
    {
      id: 'end2',
      label: 'END B',
      kind: 'gate',
      x: 198,
      y: 337,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'attack1',
      label: 'ATTACK',
      min: 0.001,
      max: 8,
      default: 0.01,
      log: true,
      unit: 's',
    },
    {
      id: 'decay1',
      label: 'DECAY',
      min: 0.003,
      max: 15,
      default: 0.3,
      log: true,
      unit: 's',
    },
    {
      id: 'attack2',
      label: 'ATTACK',
      min: 0.001,
      max: 8,
      default: 0.01,
      log: true,
      unit: 's',
    },
    {
      id: 'decay2',
      label: 'DECAY',
      min: 0.003,
      max: 15,
      default: 0.3,
      log: true,
      unit: 's',
    },
  ],
};
