// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'distortion',
  version: 2,
  name: 'GRIT',
  subtitle: 'DISTORTION',
  category: 'DISTORTION',
  order: 7,
  color: '#863f58',
  panel: '#dea3aa',
  width: 216,
  layout: 'studio',
  footer: 'FIELD / 08',
  inputs: [
    {
      id: 'in',
      label: 'SIGNAL',
      kind: 'audio',
      x: 30,
      y: 90,
      labelPosition: 'below',
    },
    {
      id: 'drive',
      label: 'DRIVE',
      kind: 'cv',
      x: 30,
      y: 182,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'out',
      label: 'OUT',
      kind: 'audio',
      x: 184,
      y: 90,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'drive',
      label: 'DRIVE',
      min: 1,
      max: 96,
      default: 8,
      log: true,
      unit: 'x',
    },
    {
      id: 'mix',
      label: 'MIX',
      min: 0,
      max: 1,
      default: 0.1,
    },
    {
      id: 'tone',
      label: 'TONE',
      min: 200,
      max: 18000,
      default: 8000,
      log: true,
      unit: 'Hz',
    },
    {
      id: 'dirt',
      label: 'DIRT',
      min: 0,
      max: 1,
      default: 0.6,
    },
    {
      id: 'mode',
      label: 'COLOUR',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
