import { readdir, readFile, writeFile, mkdir, stat, rm } from 'node:fs/promises';
import { resolve, join, dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
const generated = '// Generated by npm run modules:sync. Edit the module folders instead.\n';
async function writeChanged(path, text) {
  try {
    if ((await readFile(path, 'utf8')) === text) return;
  } catch {}
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, text);
}
async function copyJs(source, target) {
  await mkdir(target, { recursive: true });
  const entries = await readdir(source, { withFileTypes: true });
  const included = new Set();
  for (const entry of entries) {
    if (entry.name.startsWith('_')) continue;
    if (entry.isDirectory()) {
      included.add(entry.name);
      await copyJs(join(source, entry.name), join(target, entry.name));
    } else if (entry.name.endsWith('.js')) {
      included.add(entry.name);
      await writeChanged(
        join(target, entry.name),
        await readFile(join(source, entry.name), 'utf8'),
      );
    }
  }
  // This target is generated output owned by this script, never module source.
  for (const entry of await readdir(target))
    if (!included.has(entry)) await rm(join(target, entry), { recursive: true, force: true });
}
export async function syncModules(root = resolve('.')) {
  const source = join(root, 'src/modules');
  const names = (await readdir(source, { withFileTypes: true }))
    .filter((e) => e.isDirectory() && !e.name.startsWith('_'))
    .map((e) => e.name)
    .sort();
  for (const name of names) {
    if (!/^[a-z][a-z0-9-]*$/.test(name)) throw new Error(`Invalid module folder name: ${name}`);
    for (const file of ['definition.js', 'Panel.tsx', 'processor.js', 'index.ts']) {
      try {
        await stat(join(source, name, file));
      } catch {
        throw new Error(`Module ${name} needs ${file}`);
      }
    }
  }
  const bindings = names.map((name, i) => ({ name, id: `module${i}` }));
  await writeChanged(
    join(source, 'definitions.generated.js'),
    generated +
      bindings
        .map(({ name, id }) => `import { definition as ${id} } from './${name}/definition.js';`)
        .join('\n') +
      `\nexport const DEFINITIONS = {\n${bindings.map(({ name, id }) => `  '${name}': ${id},`).join('\n')}\n};\n`,
  );
  await writeChanged(
    join(source, 'audio.generated.js'),
    generated +
      "import { DEFINITIONS } from './definitions.generated.js';\n" +
      bindings.map(({ name, id }) => `import ${id} from './${name}/processor.js';`).join('\n') +
      `\nexport const AUDIO_MODULES = {\n${bindings.map(({ name, id }) => `  '${name}': { definition: DEFINITIONS['${name}'], processor: ${id} },`).join('\n')}\n};\n`,
  );
  await writeChanged(
    join(source, 'registry.generated.ts'),
    generated +
      bindings.map(({ name, id }) => `import ${id} from './${name}';`).join('\n') +
      `\nexport const MODULES = {\n${bindings.map(({ name, id }) => `  '${name}': ${id},`).join('\n')}\n};\n`,
  );
  await copyJs(source, join(root, 'public/runtime/modules'));
  await copyJs(join(root, 'src/audio'), join(root, 'public/runtime/audio'));
  return names;
}
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const names = await syncModules();
  console.log(`Synced ${names.length} modules: ${names.join(', ')}`);
}
