// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'maths',
  version: 1,
  name: 'VECTOR',
  subtitle: 'DUAL FUNCTION',
  color: '#635084',
  panel: '#c4bbdb',
  width: 640,
  layout: 'studio',
  footer: 'MODULAR',
  inputs: [
    {
      id: 'in1',
      label: 'IN 1',
      x: 42,
      y: 76,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'trig1',
      label: 'TRIG',
      x: 105,
      y: 76,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'rise1',
      label: 'RISE',
      x: 42,
      y: 285,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'both1',
      label: 'BOTH',
      x: 105,
      y: 285,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'fall1',
      label: 'FALL',
      x: 168,
      y: 285,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'cycle1',
      label: 'CYCLE',
      x: 168,
      y: 76,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'in4',
      label: 'IN 4',
      x: 462,
      y: 76,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'trig4',
      label: 'TRIG',
      x: 525,
      y: 76,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'rise4',
      label: 'RISE',
      x: 462,
      y: 285,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'both4',
      label: 'BOTH',
      x: 525,
      y: 285,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'fall4',
      label: 'FALL',
      x: 588,
      y: 285,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'cycle4',
      label: 'CYCLE',
      x: 588,
      y: 76,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'in2',
      label: 'IN 2',
      x: 260,
      y: 76,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'in3',
      label: 'IN 3',
      x: 380,
      y: 76,
      kind: 'cv',
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'ch1',
      label: 'OUT 1',
      x: 178,
      y: 338,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'ch2',
      label: 'OUT 2',
      x: 260,
      y: 205,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'ch3',
      label: 'OUT 3',
      x: 380,
      y: 205,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'ch4',
      label: 'OUT 4',
      x: 598,
      y: 338,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'eor',
      label: 'EOR',
      x: 260,
      y: 270,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'unity1',
      label: 'UNITY 1',
      x: 42,
      y: 338,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'or',
      label: 'OR',
      x: 320,
      y: 338,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'sum',
      label: 'SUM',
      x: 260,
      y: 338,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'inv',
      label: 'INV',
      x: 380,
      y: 338,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'unity4',
      label: 'UNITY 4',
      x: 462,
      y: 338,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'eoc',
      label: 'EOC',
      x: 380,
      y: 270,
      kind: 'gate',
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'rise1',
      label: 'RISE',
      min: 0.0005,
      max: 25,
      default: 0.01,
      log: true,
      unit: 's',
    },
    {
      id: 'fall1',
      label: 'FALL',
      min: 0.0005,
      max: 25,
      default: 0.25,
      log: true,
      unit: 's',
    },
    {
      id: 'curve1',
      label: 'CURVE',
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: 'cycle1',
      label: 'Cycle 1',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'rise4',
      label: 'RISE',
      min: 0.0005,
      max: 25,
      default: 0.14,
      log: true,
      unit: 's',
    },
    {
      id: 'fall4',
      label: 'FALL',
      min: 0.0005,
      max: 25,
      default: 0.14,
      log: true,
      unit: 's',
    },
    {
      id: 'curve4',
      label: 'CURVE',
      min: -1,
      max: 1,
      default: 0,
    },
    {
      id: 'cycle4',
      label: 'Cycle 4',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'att1',
      label: 'LEVEL 1',
      min: -1,
      max: 1,
      default: 1,
      unit: 'x',
    },
    {
      id: 'att2',
      label: 'LEVEL 2',
      min: -2,
      max: 2,
      default: 0,
      unit: 'x',
    },
    {
      id: 'att3',
      label: 'LEVEL 3',
      min: -2,
      max: 2,
      default: 0,
      unit: 'x',
    },
    {
      id: 'att4',
      label: 'LEVEL 4',
      min: -1,
      max: 1,
      default: 1,
      unit: 'x',
    },
  ],
  hidden: false,
  headerLayout: 'compact',
  portStyle: 'badge',
  category: 'FUNCTION',
  order: 2.5,
};
