// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'logic',
  version: 1,
  name: 'LOGIC',
  subtitle: 'GATES + COMPARE',
  category: 'LOGIC',
  order: 12.3,
  color: '#596844',
  panel: '#cbd6a6',
  width: 320,
  layout: 'studio',
  headerLayout: 'compact',
  portStyle: 'badge',
  inputs: [
    {
      id: 'a',
      label: 'A',
      x: 36,
      y: 85,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'b',
      label: 'B',
      x: 36,
      y: 154,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'signal',
      label: 'SIGNAL',
      x: 36,
      y: 265,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'threshold',
      label: 'THRESH CV',
      x: 36,
      y: 331,
      kind: 'cv',
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'and',
      label: 'AND',
      x: 181,
      y: 85,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'or',
      label: 'OR',
      x: 280,
      y: 85,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'xor',
      label: 'XOR',
      x: 181,
      y: 154,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'not',
      label: 'NOT A',
      x: 280,
      y: 154,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'high',
      label: 'ABOVE',
      x: 280,
      y: 265,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'low',
      label: 'BELOW',
      x: 280,
      y: 331,
      kind: 'gate',
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'threshold',
      label: 'THRESHOLD',
      min: -10,
      max: 10,
      default: 0,
      unit: 'V',
    },
    {
      id: 'hysteresis',
      label: 'HYSTERESIS',
      min: 0.001,
      max: 2,
      default: 0.05,
      unit: 'V',
    },
  ],
};
