// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'a155',
  version: 1,
  name: 'PATH²',
  subtitle: 'DUAL SEQUENCER',
  color: '#395d7c',
  panel: '#a9c8df',
  width: 752,
  layout: 'faceplate',
  footer: 'FIELD / ARCHIVE',
  inputs: [
    {
      id: 'start',
      label: 'Start',
      x: 696,
      y: 59,
      kind: 'gate',
    },
    {
      id: 'stop',
      label: 'Stop',
      x: 696,
      y: 97,
      kind: 'gate',
    },
    {
      id: 'clock',
      label: 'Clock',
      x: 696,
      y: 135,
      kind: 'gate',
    },
    {
      id: 'reset',
      label: 'Reset',
      x: 696,
      y: 173,
      kind: 'gate',
    },
    {
      id: 'ext1',
      label: '1',
      x: 35,
      y: 331,
      kind: 'audio',
    },
    {
      id: 'ext2',
      label: '2',
      x: 95,
      y: 331,
      kind: 'audio',
    },
    {
      id: 'ext3',
      label: '3',
      x: 155,
      y: 331,
      kind: 'audio',
    },
    {
      id: 'ext4',
      label: '4',
      x: 215,
      y: 331,
      kind: 'audio',
    },
    {
      id: 'ext5',
      label: '5',
      x: 275,
      y: 331,
      kind: 'audio',
    },
    {
      id: 'ext6',
      label: '6',
      x: 335,
      y: 331,
      kind: 'audio',
    },
    {
      id: 'ext7',
      label: '7',
      x: 395,
      y: 331,
      kind: 'audio',
    },
    {
      id: 'ext8',
      label: '8',
      x: 455,
      y: 331,
      kind: 'audio',
    },
    {
      id: 'sh1',
      label: 'S&H Ctrl.',
      x: 633,
      y: 255,
      kind: 'gate',
    },
    {
      id: 'glide1',
      label: 'Glide Ctrl.',
      x: 696,
      y: 255,
      kind: 'gate',
    },
    {
      id: 'sh2',
      label: 'S&H Ctrl.',
      x: 633,
      y: 333,
      kind: 'gate',
    },
    {
      id: 'glide2',
      label: 'Glide Ctrl.',
      x: 696,
      y: 333,
      kind: 'gate',
    },
  ],
  outputs: [
    {
      id: 'trig1',
      label: 'Trig 1',
      x: 633,
      y: 59,
      kind: 'gate',
    },
    {
      id: 'trig2',
      label: 'Trig 2',
      x: 633,
      y: 97,
      kind: 'gate',
    },
    {
      id: 'trig3',
      label: 'Trig 3',
      x: 633,
      y: 135,
      kind: 'gate',
    },
    {
      id: 'gate',
      label: 'Gate',
      x: 633,
      y: 173,
      kind: 'gate',
    },
    {
      id: 'pre1',
      label: 'Pre Out',
      x: 633,
      y: 215,
      kind: 'cv',
    },
    {
      id: 'post1',
      label: 'Post Out',
      x: 696,
      y: 215,
      kind: 'cv',
    },
    {
      id: 'pre2',
      label: 'Pre Out',
      x: 633,
      y: 293,
      kind: 'cv',
    },
    {
      id: 'post2',
      label: 'Post Out',
      x: 696,
      y: 293,
      kind: 'cv',
    },
  ],
  params: [
    {
      id: 'range',
      label: 'Range',
      min: 0,
      max: 2,
      default: 1,
      step: 1,
      smooth: false,
    },
    {
      id: 'scale',
      label: 'Scale',
      min: 0,
      max: 6.5,
      default: 5,
      unit: 'V',
    },
    {
      id: 'glide1',
      label: 'Glide',
      min: 0,
      max: 2,
      default: 0,
      unit: 's',
    },
    {
      id: 'glide2',
      label: 'Glide',
      min: 0,
      max: 2,
      default: 0,
      unit: 's',
    },
    {
      id: 'a1',
      label: '1',
      min: 0,
      max: 1,
      default: 0,
      smooth: false,
    },
    {
      id: 'b1',
      label: '1',
      min: 0,
      max: 1,
      default: 0.5,
      smooth: false,
    },
    {
      id: 'top1',
      label: 'Step 1 trigger track',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'bottom1',
      label: 'Step 1 gate track',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
    {
      id: 'a2',
      label: '2',
      min: 0,
      max: 1,
      default: 0,
      smooth: false,
    },
    {
      id: 'b2',
      label: '2',
      min: 0,
      max: 1,
      default: 0.5,
      smooth: false,
    },
    {
      id: 'top2',
      label: 'Step 2 trigger track',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'bottom2',
      label: 'Step 2 gate track',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
    {
      id: 'a3',
      label: '3',
      min: 0,
      max: 1,
      default: 0,
      smooth: false,
    },
    {
      id: 'b3',
      label: '3',
      min: 0,
      max: 1,
      default: 0.5,
      smooth: false,
    },
    {
      id: 'top3',
      label: 'Step 3 trigger track',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'bottom3',
      label: 'Step 3 gate track',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
    {
      id: 'a4',
      label: '4',
      min: 0,
      max: 1,
      default: 0,
      smooth: false,
    },
    {
      id: 'b4',
      label: '4',
      min: 0,
      max: 1,
      default: 0.5,
      smooth: false,
    },
    {
      id: 'top4',
      label: 'Step 4 trigger track',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'bottom4',
      label: 'Step 4 gate track',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
    {
      id: 'a5',
      label: '5',
      min: 0,
      max: 1,
      default: 0,
      smooth: false,
    },
    {
      id: 'b5',
      label: '5',
      min: 0,
      max: 1,
      default: 0.5,
      smooth: false,
    },
    {
      id: 'top5',
      label: 'Step 5 trigger track',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'bottom5',
      label: 'Step 5 gate track',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
    {
      id: 'a6',
      label: '6',
      min: 0,
      max: 1,
      default: 0,
      smooth: false,
    },
    {
      id: 'b6',
      label: '6',
      min: 0,
      max: 1,
      default: 0.5,
      smooth: false,
    },
    {
      id: 'top6',
      label: 'Step 6 trigger track',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'bottom6',
      label: 'Step 6 gate track',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
    {
      id: 'a7',
      label: '7',
      min: 0,
      max: 1,
      default: 0,
      smooth: false,
    },
    {
      id: 'b7',
      label: '7',
      min: 0,
      max: 1,
      default: 0.5,
      smooth: false,
    },
    {
      id: 'top7',
      label: 'Step 7 trigger track',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'bottom7',
      label: 'Step 7 gate track',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
    {
      id: 'a8',
      label: '8',
      min: 0,
      max: 1,
      default: 0,
      smooth: false,
    },
    {
      id: 'b8',
      label: '8',
      min: 0,
      max: 1,
      default: 0.5,
      smooth: false,
    },
    {
      id: 'top8',
      label: 'Step 8 trigger track',
      min: 0,
      max: 2,
      default: 0,
      step: 1,
      smooth: false,
    },
    {
      id: 'bottom8',
      label: 'Step 8 gate track',
      min: 0,
      max: 2,
      default: 2,
      step: 1,
      smooth: false,
    },
  ],
  hidden: true,
};
