// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'shift-register',
  version: 1,
  name: 'RELAY',
  subtitle: 'CV DELAY / 4',
  category: 'CV DELAY',
  order: 12.2,
  color: '#476d68',
  panel: '#a8cfbf',
  width: 280,
  layout: 'studio',
  headerLayout: 'compact',
  portStyle: 'badge',
  inputs: [
    {
      id: 'in',
      label: 'CV IN',
      x: 38,
      y: 85,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'clock',
      label: 'CLOCK',
      x: 38,
      y: 162,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'reset',
      label: 'RESET',
      x: 38,
      y: 239,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'hold',
      label: 'HOLD',
      x: 38,
      y: 316,
      kind: 'gate',
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'now',
      label: 'NOW',
      x: 242,
      y: 74,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'tap1',
      label: '1 CLK',
      x: 242,
      y: 136,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'tap2',
      label: '2 CLK',
      x: 242,
      y: 198,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'tap3',
      label: '3 CLK',
      x: 242,
      y: 260,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'tap4',
      label: '4 CLK',
      x: 242,
      y: 322,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'out',
      label: 'DELAY',
      x: 139,
      y: 317,
      kind: 'cv',
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'tap',
      label: 'DELAY',
      min: 1,
      max: 4,
      default: 4,
      step: 1,
      smooth: false,
      unit: 'steps',
    },
  ],
};
