// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'envelope',
  version: 1,
  name: 'BLOOM',
  subtitle: 'ENV',
  category: 'ENV',
  order: 1,
  color: '#8a443d',
  panel: '#efb2a0',
  width: 232,
  layout: 'studio',
  footer: 'FIELD / 02',
  inputs: [
    {
      id: 'gate',
      label: 'GATE',
      kind: 'gate',
      x: 34,
      y: 79,
      labelPosition: 'below',
    },
    {
      id: 'retrigger',
      label: 'RETRIG',
      kind: 'gate',
      x: 91,
      y: 79,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'env',
      label: 'ENV',
      kind: 'cv',
      x: 88,
      y: 329,
      labelPosition: 'below',
    },
    {
      id: 'inv',
      label: '−ENV',
      kind: 'cv',
      x: 152,
      y: 329,
      labelPosition: 'below',
    },
    {
      id: 'end',
      label: 'END',
      kind: 'gate',
      x: 198,
      y: 79,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'attack',
      label: 'ATTACK',
      min: 0.001,
      max: 8,
      default: 0.01,
      log: true,
      unit: 's',
    },
    {
      id: 'decay',
      label: 'DECAY',
      min: 0.003,
      max: 10,
      default: 0.18,
      log: true,
      unit: 's',
    },
    {
      id: 'sustain',
      label: 'SUSTAIN',
      min: 0,
      max: 1,
      default: 0.45,
    },
    {
      id: 'release',
      label: 'RELEASE',
      min: 0.003,
      max: 15,
      default: 0.3,
      log: true,
      unit: 's',
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
