// @ts-check
/** @type {import('../types').ModuleDefinition} */
export const definition = {
  type: 'envelope',
  version: 2,
  name: 'BLOOM',
  subtitle: 'VC ADSR',
  category: 'ENV',
  order: 1,
  color: '#8a443d',
  panel: '#efb2a0',
  width: 232,
  layout: 'studio',
  footer: 'FIELD / 02',
  inputs: [
    {
      id: 'gate',
      label: 'GATE',
      kind: 'gate',
      x: 198,
      y: 78,
      labelPosition: 'below',
    },
    {
      id: 'retrigger',
      label: 'RETRIG',
      kind: 'gate',
      x: 198,
      y: 143,
      labelPosition: 'below',
    },
    {
      id: 'attack',
      label: 'A CV',
      kind: 'cv',
      x: 120,
      y: 88,
      labelPosition: 'below',
    },
    {
      id: 'decay',
      label: 'D CV',
      kind: 'cv',
      x: 120,
      y: 167,
      labelPosition: 'below',
    },
    {
      id: 'sustain',
      label: 'S CV',
      kind: 'cv',
      x: 120,
      y: 246,
      labelPosition: 'below',
    },
    {
      id: 'release',
      label: 'R CV',
      kind: 'cv',
      x: 120,
      y: 325,
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'env',
      label: 'ENV',
      kind: 'cv',
      x: 198,
      y: 208,
      labelPosition: 'below',
    },
    {
      id: 'inv',
      label: '−ENV',
      kind: 'cv',
      x: 198,
      y: 273,
      labelPosition: 'below',
    },
    {
      id: 'end',
      label: 'END',
      kind: 'gate',
      x: 198,
      y: 338,
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'attack',
      label: 'ATTACK',
      min: 0.001,
      max: 8,
      default: 0.01,
      log: true,
      unit: 's',
    },
    {
      id: 'decay',
      label: 'DECAY',
      min: 0.003,
      max: 10,
      default: 0.18,
      log: true,
      unit: 's',
    },
    {
      id: 'sustain',
      label: 'SUSTAIN',
      min: 0,
      max: 1,
      default: 0.45,
    },
    {
      id: 'release',
      label: 'RELEASE',
      min: 0.003,
      max: 15,
      default: 0.3,
      log: true,
      unit: 's',
    },
  ],
  headerLayout: 'compact',
  portStyle: 'badge',
};
