// @ts-check
/** @type {import("../types").ModuleDefinition} */
export const definition = {
  type: 'random',
  version: 1,
  name: 'CHANCE',
  subtitle: 'RANDOM / S&H',
  category: 'RANDOM',
  order: 12,
  color: '#7c4e39',
  panel: '#dfb095',
  width: 300,
  layout: 'studio',
  headerLayout: 'compact',
  portStyle: 'badge',
  inputs: [
    {
      id: 'clock',
      label: 'CLOCK',
      x: 34,
      y: 85,
      kind: 'gate',
      labelPosition: 'below',
    },
    {
      id: 'sample',
      label: 'SAMPLE',
      x: 34,
      y: 166,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'hold',
      label: 'HOLD',
      x: 34,
      y: 247,
      kind: 'gate',
      labelPosition: 'below',
    },
  ],
  outputs: [
    {
      id: 'step',
      label: 'STEP',
      x: 266,
      y: 85,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'smooth',
      label: 'SMOOTH',
      x: 266,
      y: 166,
      kind: 'cv',
      labelPosition: 'below',
    },
    {
      id: 'noise',
      label: 'NOISE',
      x: 266,
      y: 247,
      kind: 'audio',
      labelPosition: 'below',
    },
    {
      id: 'gate',
      label: 'GATE',
      x: 266,
      y: 328,
      kind: 'gate',
      labelPosition: 'below',
    },
  ],
  params: [
    {
      id: 'rate',
      label: 'RATE',
      min: 0.02,
      max: 40,
      default: 2,
      log: true,
      unit: 'Hz',
    },
    {
      id: 'range',
      label: 'RANGE',
      min: 0,
      max: 10,
      default: 5,
      unit: 'V',
    },
    {
      id: 'slew',
      label: 'SMOOTH',
      min: 0.001,
      max: 10,
      default: 0.35,
      log: true,
      unit: 's',
    },
    {
      id: 'chance',
      label: 'CHANCE',
      min: 0,
      max: 1,
      default: 0.5,
    },
    {
      id: 'polarity',
      label: 'RANGE',
      min: 0,
      max: 1,
      default: 0,
      step: 1,
      smooth: false,
    },
  ],
};
